<?php

return [
    'default' => env('DB_CONNECTION'),
    'backup' => env('BACKUP_DB_CONNECTION'),
    'olap' => env('OLAP_DB_CONNECTION'),
    'log' => env('LOG_DB_CONNECTION'),
    'warehouse' => env('WAREHOUSE_DB_CONNECTION'),
    'monitoring' => env('OLAP_DB_CONNECTION'),
    'getdiskon' => env('GETDISKON_DB_CONNECTION'),
    'fetch' => PDO::FETCH_CLASS,
    'connections' => [
        env('DB_CONNECTION') => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST'),
            'database'  => env('DB_DATABASE'),
            'username'  => env('DB_USERNAME'),
            'password'  => env('DB_PASSWORD'),
            'charset'   => 'utf8',
            'collation' => 'utf8_general_ci',
            'prefix'    => '',
            'strict'    => false,
        ],
        env('WAREHOUSE_DB_CONNECTION') => [
            'driver'    => 'mysql',
            'host'      => env('WAREHOUSE_DB_HOST'),
            'database'  => env('WAREHOUSE_DB_DATABASE'),
            'username'  => env('WAREHOUSE_DB_USERNAME'),
            'password'  => env('WAREHOUSE_DB_PASSWORD'),
            'charset'   => 'utf8',
            'collation' => 'utf8_general_ci',
            'prefix'    => '',
            'strict'    => false,
        ],
        env('BACKUP_DB_CONNECTION') => [
            'driver'    => 'mysql',
            'host'      => env('BACKUP_DB_HOST'),
            'database'  => env('BACKUP_DB_DATABASE'),
            'username'  => env('BACKUP_DB_USERNAME'),
            'password'  => env('BACKUP_DB_PASSWORD'),
            'charset'   => 'utf8',
            'collation' => 'utf8_general_ci',
            'prefix'    => '',
            'strict'    => false,
        ],
        env('OLAP_DB_CONNECTION') => [
            'driver'    => 'mysql',
            'host'      => env('OLAP_DB_HOST'),
            'database'  => env('OLAP_DB_DATABASE'),
            'username'  => env('OLAP_DB_USERNAME'),
            'password'  => env('OLAP_DB_PASSWORD'),
            'charset'   => 'utf8',
            'collation' => 'utf8_general_ci',
            'prefix'    => '',
            'strict'    => false,
        ],
        env('GETDISKON_DB_CONNECTION') => [
            'driver'    => 'mysql',
            'host'      => env('GETDISKON_DB_HOST'),
            'database'  => env('GETDISKON_DB_DATABASE'),
            'username'  => env('GETDISKON_DB_USERNAME'),
            'password'  => env('GETDISKON_DB_PASSWORD'),
            'charset'   => 'utf8',
            'collation' => 'utf8_general_ci',
            'prefix'    => '',
            'strict'    => false,
        ],
        env('LOG_DB_CONNECTION') => [
            'driver'    => 'mysql',
            'host'      => env('LOG_DB_HOST'),
            'database'  => env('LOG_DB_DATABASE'),
            'username'  => env('LOG_DB_USERNAME'),
            'password'  => env('LOG_DB_PASSWORD'),
            'charset'   => 'utf8',
            'collation' => 'utf8_general_ci',
            'prefix'    => '',
            'strict'    => false,
        ],
        env('QUEUE_DB_CONNECTION') => [
            'driver'    => 'mysql',
            'host'      => env('QUEUE_DB_HOST'),
            'database'  => env('QUEUE_DB_DATABASE'),
            'username'  => env('QUEUE_DB_USERNAME'),
            'password'  => env('QUEUE_DB_PASSWORD'),
            'charset'   => 'utf8',
            'collation' => 'utf8_general_ci',
            'prefix'    => '',
            'strict'    => false,
        ],
    ]
];
